[build]
  command = "npm run build:netlify"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  GENERATE_SOURCEMAP = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  # Note: REACT_APP_GOOGLE_MAPS_API_KEY should be set in Netlify UI
  # Do not add the actual API key here

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://maps.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.googleapis.com https://*.gstatic.com https://*.squarespace-cdn.com https://example.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.googleapis.com; frame-src 'self' https://*.googleapis.com; object-src 'none'"
